Protobuf for verifier -> storage
RainBlock/rainblock-protocol pull request #1
Opened 2019-03-01 03:33 UTC by SoujanyaPonnapalli

This protobuf mainly captures the following API for the interaction between the verifier -> storage:
1. PutGenesis ( genesisBlock, putOps )
2. Update ( block, putOps, delOps )
3. GetBlockByNumber ( blockNum ) : block
4. GetBlockByHash ( blockHash ) : block
5. Get (key, rootHash) : value, proof
6. verifyWitness (key, root, witness) : boolean

We need another function as discussed, which returns the newest block miner by a miner
7. GetBlockByMiner (minerId) => Block

2019-03-01 03:52 UTC, amytai reviewed
Thanks for starting this! I think generally, it would be helpful to put your messages in the gRPC format as well (i.e. -- specify the RPCs that go along with the message pairs you've laid out).

2019-03-01 03:52 UTC, amytai commented on verif-store.proto
> +  uint64 blockNumber = 1;
This should actually be `int64`, as this is what the EVMC expects.

2019-03-01 03:52 UTC, amytai commented on verif-store.proto
> +message getBlockByNumberInputMsg {
I'll let Michael comment on whether the verifier needs this specific function, but on the client side, we need a `getBlockHashByNumber` RPC (rather than a `getBlock` function), which has a slightly different return value.

2019-03-01 03:52 UTC, amytai commented on verif-store.proto
> +message getBlockByMinerInputMsg {
What is this used for?

2019-03-01 03:54 UTC, SoujanyaPonnapalli commented on verif-store.proto
> +  uint64 blockNumber = 1;
Awesome! I'll fix it.

2019-03-01 04:00 UTC, SoujanyaPonnapalli commented on verif-store.proto
> +message getBlockByNumberInputMsg {
Yeah, I have noticed that there are two functions getBlockByHash and getBlockHashByNumber. But I felt, a single call returning a block could save a round trip communication cost for getting a block of data either by number or by hash. That's the reason I went ahead with retuning the block. Let's see what Michael has to say.

2019-03-01 04:05 UTC, SoujanyaPonnapalli commented on verif-store.proto
> +message getBlockByMinerInputMsg {
I don't know the underlying details but, apparently for having deterministic randomness in smart contracts, clients can query the latest blockHash/block mined by a particular miner and insert it in their contract.

2019-03-01 04:16 UTC, amytai commented on verif-store.proto
> +message getBlockByMinerInputMsg {
Hm, you might be thinking of the "miner ID" (miner who mined this txn) and the "block number of the block that this txn belongs to" info that we sometimes need to get for a transaction. I don't believe we need this function at all (in particular, I don't think you will need to build an index on minerID for the blocks). But again, I'll let Michael confirm.

2019-03-01 04:16 UTC, no2chem commented on verif-store.proto
> +message getBlockByNumberInputMsg {
Actually, I think a `getBlockHash` RPC which fetches all N-256 hashes, including unconfirmed forks, would be better.

2019-03-01 04:19 UTC, no2chem commented on verif-store.proto
> +message putGenesisMsg {
This isn't a verifier->storage message but a tx->storage message
Thinking about it further, maybe it's not a message at all, but what you start the storage node with. I'd omit it for now.

2019-03-01 04:19 UTC, no2chem commented on verif-store.proto
> +message updateMsg {
also a tx->storage message

2019-03-01 04:20 UTC, amytai commented on verif-store.proto
> +message getBlockByNumberInputMsg {
@no2chem -- does the verifier actually need such an RPC?
I think this belongs (in fact, I've already defined it) in the client <-> storage node API. The verifier might use this RPC, but I think the response will be a single hash, and not all unconfirmed forks.

2019-03-01 04:22 UTC, no2chem commented on verif-store.proto
> +message getBlockByMinerInputMsg {
Yes, also the technical Ethereum term is `coinbase`. I think maybe we need a get recent `coinbase` function, rather than a get all blocks by `coinbase` function

2019-03-01 04:22 UTC, no2chem commented
I think this is a great start, - see my comments
Also, I don't think 7 is necessary. I think at most we would have a getRecentMiner() call.

2019-03-01 04:32 UTC, SoujanyaPonnapalli commented on verif-store.proto
> +message getBlockByMinerInputMsg {
I'm confused. So, what is it that we want exactly?
getRecent (coinbase) => hash of the most recent block it mined? Or is it 
getRecent() => coinbase of the most recent block that the storage node knows of?

2019-03-01 04:42 UTC, SoujanyaPonnapalli commented on verif-store.proto
> +message updateMsg {
Right; will we have a different proto definition for tx->storage?
Is verification + tx execution not being done by a same node? Not sure I understand why we need this separation.

2019-03-15 16:32 UTC, no2chem requested changes
Is any of this updated? It seems to be missing the one RPC the verifier actually needs, which is put/insert (?)

2019-03-18 19:28 UTC, SoujanyaPonnapalli commented
Updated the protobuf to have the single call required for verifier and storage communication.

2019-03-18 20:32 UTC, no2chem requested changes
Looks OK, but I think it needs comments

2019-03-18 20:32 UTC, no2chem commented on src/verifierStorage.proto
> +//** Update (merkle_tree_nodes, operations) => ();
Is there a reason there's two asterisks here?

2019-03-18 20:32 UTC, no2chem commented on src/verifierStorage.proto
> +message EmptyMsg {}
I think you should use the default:

```
import "google/protobuf/empty.proto";
```

and use

```
google.protobuf.Empty
```

instead of defining your own message

2019-03-18 20:32 UTC, no2chem commented on src/verifierStorage.proto
> +message UpdateOp {
Comments and or description

2019-03-19 02:28 UTC, SoujanyaPonnapalli commented on src/verifierStorage.proto
> +message UpdateOp {
Added comments to the protobuf

2019-03-19 02:28 UTC, SoujanyaPonnapalli commented on src/verifierStorage.proto
> +message EmptyMsg {}
Fixed!

2019-03-19 05:17 UTC, no2chem requested changes
Good, but the comments need a little more detail

2019-03-19 05:17 UTC, no2chem commented on src/verifierStorage.proto
> +  rpc Update(UpdateMsg) returns (google.protobuf.Empty);
For example, ```// Updates the storage node with a new block```

2019-03-19 05:17 UTC, no2chem commented on src/verifierStorage.proto
> +// merkle_tree_nodes : The nodes in the initial layers of the global state trie
How are these nodes serialized? Why is it repeated bytes? Maybe take a look at clientVerifier.proto?

2019-03-19 05:17 UTC, no2chem commented on src/verifierStorage.proto
> +// operations        : An rlp_block and a list of state update operations
How does operations include an `rlp_block`? Isn't a `rlp_block` a separate field?

2019-03-19 05:17 UTC, no2chem commented on src/verifierStorage.proto
> +// Update            : (merkle_tree_nodes, operations) => ();
What does this mean?

2019-03-19 05:17 UTC, no2chem commented on src/verifierStorage.proto
> +// UpdateMsg
Maybe a description of what UpdateMsg is supposed to be for?

2019-03-19 05:17 UTC, no2chem commented on src/verifierStorage.proto
> +  bytes account = 1;
Is there some format to an account?

2019-03-19 05:17 UTC, no2chem commented on src/verifierStorage.proto
> +  bytes value = 2;
What is the format of this?

2019-03-19 18:37 UTC, SoujanyaPonnapalli commented
Updated the comments and the descriptions as per the review.

2019-03-19 18:38 UTC, SoujanyaPonnapalli commented
Added formats and updated the description in the comments.

2019-03-19 19:10 UTC, SoujanyaPonnapalli commented on src/verifierStorage.proto
> +// merkle_tree_nodes : The nodes in the initial layers of the global state trie
Updated it to resemble the witness encoding as defined in clientVerifier.proto

2019-03-19 20:09 UTC, no2chem requested changes
See comments

2019-03-19 20:09 UTC, no2chem commented on src/verifierStorage.proto
> +  bytes account = 1; // hex buffer as bytes
Well. We know the type. What's important is whether or not this is big endian, little endian, and any relevant padding. Probably you want to say `// 20 byte big endian account number`

2019-03-19 20:09 UTC, no2chem commented on src/verifierStorage.proto
> +  bytes value = 2; // bigint as bytes
`bigint` is a javascript type. A `bigint` can be encoded in a lot of ways. You probably want a 32 byte big endian unsigned integer, since this will match the type used by the EVM.

2019-03-19 20:09 UTC, no2chem commented on src/verifierStorage.proto
> +  uint32 changes = 3; // number as bytes
`number` is a javascript type. Also, this doesn't seem to be bytes if its `uint32`...

2019-03-19 20:09 UTC, no2chem commented on src/verifierStorage.proto
> +  bytes account = 1; // hex buffer
What is a `hex` buffer? Do you mean a hex string? Why would we want to send a hex string?

2019-03-19 20:09 UTC, no2chem commented on src/verifierStorage.proto
> +  bytes account = 1; // hex buffer as bytes
same as above

2019-03-19 20:09 UTC, no2chem commented on src/verifierStorage.proto
> +  bytes value = 2; // bigint as bytes
same as above

2019-03-19 20:09 UTC, no2chem commented on src/verifierStorage.proto
> +  bytes code = 3; // hex buffer as bytes
same as above

2019-03-19 20:09 UTC, no2chem commented on src/verifierStorage.proto
> +  bytes account = 1; // hex buffer as bytes
same as above

2019-03-19 20:09 UTC, no2chem commented on src/verifierStorage.proto
> +  bytes value = 2; // bigint as bytes
same as above

2019-03-19 20:09 UTC, no2chem commented on src/verifierStorage.proto
> +// key, value : An account's storage entry to be inserted or updated
Instead of putting the description here, just put it on top of the field

2019-03-19 20:50 UTC, SoujanyaPonnapalli commented on src/verifierStorage.proto
> +  bytes code = 3; // hex buffer as bytes
Will you be sending an RLP encoded big endian buffer as code?

2019-03-20 00:48 UTC, no2chem requested changes
I'm not trying to be pedantic here, but it does seem that there is some confusion over the fields and understanding of endianness. Take a look at the comments, there are some field comments which I don't understand.

2019-03-20 00:48 UTC, no2chem commented on src/verifierStorage.proto
> +  bytes code = 3; // RLP encoded big endian buffer
Why is the code big endian? What does this mean for a non-numerical value? And why is it RLP encoded?

2019-03-20 00:48 UTC, no2chem commented on src/verifierStorage.proto
> +  uint32 changes = 3; // big endian uint32 number
isn't the byte order of a protobuf numerical type determined by the spec - you don't need to write it here, and it's **_not_** big endian: https://developers.google.com/protocol-buffers/docs/encoding

2019-03-20 01:13 UTC, SoujanyaPonnapalli commented on src/verifierStorage.proto
> +  uint32 changes = 3; // big endian uint32 number
Got it, thanks for the pointer.

2019-03-20 01:15 UTC, SoujanyaPonnapalli commented on src/verifierStorage.proto
> +  bytes code = 3; // RLP encoded big endian buffer
Wasn't sure how the code size would be determined. As rlp encoding encodes the buffer with its length, I thought it would be good to encode the buffer.

2019-03-20 04:05 UTC, no2chem commented on src/verifierStorage.proto
> +  bytes code = 3; // RLP encoded big endian buffer
Why would that be necessary? The whole point of the protobuf bytes field is that the protobuf implementation encodes that for you, isn't it? How else would the protobuf implementation delineate fields?

2019-03-20 04:12 UTC, SoujanyaPonnapalli commented on src/verifierStorage.proto
> +  bytes code = 3; // RLP encoded big endian buffer
I agree it was a mistake. I fixed the comments. Let me know if it looks good to you now.

2019-03-20 04:13 UTC, no2chem requested changes
okay, could you move the comments down on top of the field?

2019-03-20 04:13 UTC, no2chem commented on src/verifierStorage.proto
> +// account : Address of the account to be modified
Can you please move these comments to the respective fields?

2019-03-20 04:15 UTC, SoujanyaPonnapalli commented on src/verifierStorage.proto
> +// account : Address of the account to be modified
Okay will do!

2019-03-20 04:27 UTC, SoujanyaPonnapalli commented
Let me know if it looks good.

2019-03-20 17:44 UTC, no2chem approved these changes
Ok, LGTM now.

2019-03-20 17:45 UTC, merged